import { useState, useEffect } from 'react';
import './App.css';
import { io } from "socket.io-client";
import { SignedIn, SignedOut, SignInButton, UserButton, useUser } from '@clerk/clerk-react';
import { SequenceBuilder } from './components/dashboard/SequenceBuilder'; 
import { PublicSequenceRunner } from './components/dashboard/PublicSequenceRunner.tsx';

// =========================================================================
// 1. COMPONENT IMPORTS
// =========================================================================

import { AuditoryRepetitionWorkspace, AuditoryRepetitionRunner } from './components/tests/AuditoryRepetition.tsx';
import { VisualAssociationWorkspace, VisualAssociationRunner } from './components/tests/VisualAssociationTemplate';
import { ReadingAloudWorkspace, ReadingAloudRunner } from './components/tests/ReadingAloud';
import { BinaryChoiceWorkspace, BinaryChoiceRunner } from './components/tests/BinaryChoiceTemplate';
import { VisualTargetWorkspace, TargetRunnerEngine } from './components/tests/VisualTargetIdentification';

// NEW: Naming Task Imports
import { NamingTaskWorkspace, NamingTaskRunner } from './components/tests/NamingTask';

import { PatientIntakeWorkspace } from './components/patients/PatientIntakeForm';
import { PatientBank } from './components/patients/PatientBank';
import type { PatientIntake } from './types/patient';

// NEW: Dynamic API URL for Render vs Localhost
const API_URL = import.meta.env.VITE_API_URL || 'https://leviva-backend.onrender.com';
// =========================================================================
// 2. TYPES & INTERFACES FOR THE TEST BANK
// =========================================================================

// NEW: Added 'Naming' to TestCategory
export type TestCategory = 'Auditory' | 'VisualAssociation' | 'ReadingAloud' | 'BinaryChoice' | 'TargetID' | 'Naming';

export interface SavedTest {
  id: string;
  title: string;
  description: string; 
  category: TestCategory;
  folder: string; 
  configData: any; 
  dateCreated: string;
  lastModified: string; 
}

const loadFromStorage = (key: string, fallback: any) => {
  try {
    const saved = localStorage.getItem(key);
    return saved ? JSON.parse(saved) : fallback;
  } catch (e) {
    return fallback;
  }
};

// NEW: Added 'Naming' to DEFAULT_FOLDERS
const DEFAULT_FOLDERS = ['Auditory', 'VisualAssociation', 'ReadingAloud', 'BinaryChoice', 'TargetID', 'Naming'];

// =========================================================================
// 3. MAIN APP COMPONENT
// =========================================================================

export default function App() {

useEffect(() => {
  const socket = io(API_URL);
  socket.on("connect", () => {
    console.log("✅ Successfully connected to the Sync Server!", socket.id);
  });
}, []);

// Parse "/run/:id" links (e.g. the shareable links generated by "Get Shareable Link")
// so opening one directly loads that sequence instead of silently falling back to Home.
// This is also how we know a session is a REAL participant hitting the standalone link,
// as opposed to an admin clicking "Run Sequence" from inside the dashboard — see
// `isPublicLinkAccess` below, which locks down PublicSequenceRunner's navigation controls.
useEffect(() => {
  const match = window.location.pathname.match(/^\/run\/([a-zA-Z0-9]+)$/);
  if (match) {
    setActiveSequenceId(match[1]);
    setIsPublicLinkAccess(true);
    setCurrentView('public-run-sequence');
  }
}, []);

  // --- GLOBAL STATE ---
  const [currentView, setCurrentView] = useState<string>('home');
  const [activeRunConfig, setActiveRunConfig] = useState<SavedTest | null>(null);

  // Role read from Clerk's publicMetadata (set manually via Clerk Dashboard -> Users ->
  // Metadata for now, e.g. { "role": "lab_admin" } or { "role": "clinician" }).
  // Irrelevant/undefined on the public /run/:id tunnel since that path never renders
  // anything gated by SignedIn in the first place.
  const { user } = useUser();
  const userRole = (user?.publicMetadata as { role?: 'clinician' | 'lab_admin' } | undefined)?.role;
  const isLabAdmin = userRole === 'lab_admin';
  
  const [testBank, setTestBank] = useState<SavedTest[]>(() => loadFromStorage('leviva_testBank', [])); 
  const [patientBank, setPatientBank] = useState<PatientIntake[]>(() => loadFromStorage('leviva_patientBank', []));
  
  const [customFolders, setCustomFolders] = useState<string[]>(() => loadFromStorage('leviva_folders', DEFAULT_FOLDERS));

  const [editTarget, setEditTarget] = useState<SavedTest | null>(null);
  const [expandedFolder, setExpandedFolder] = useState<string | null>(null);

  const [editPatientTarget, setEditPatientTarget] = useState<PatientIntake | null>(null);
  const [activePatientForTesting, setActivePatientForTesting] = useState<PatientIntake | null>(null);

  const [sequenceBank, setSequenceBank] = useState<any[]>([]);
  const [activeSequenceId, setActiveSequenceId] = useState<string | null>(null);
  const [editSequenceTarget, setEditSequenceTarget] = useState<any | null>(null);
  // True only when reached via the real "/run/:id" standalone link (see the deep-link
  // useEffect above). False for the admin's in-dashboard "Run Sequence" preview button.
  const [isPublicLinkAccess, setIsPublicLinkAccess] = useState(false);



  const openSequenceBank = async () => {
    try {
      // 1. Fetch live sequences from MongoDB cloud storage
      const response = await fetch(`${API_URL}/api/sequences`);
      const cloudSequences = await response.json();

      // 2. Also check local storage backup for any offline additions
      const localSequences = JSON.parse(localStorage.getItem('leviva_sequenceBank') || '[]');

      // 3. Merge them together (preferring cloud data, falling back/adding local ones if any exist)
      const mergedMap = new Map();
      cloudSequences.forEach((seq: any) => mergedMap.set(seq._id, seq));
      localSequences.forEach((seq: any) => {
        if (!mergedMap.has(seq._id)) mergedMap.set(seq._id, seq);
      });

      setSequenceBank(Array.from(mergedMap.values()));
      setCurrentView('sequence-bank');
    } catch (error) {
      console.error("Failed to fetch sequences from cloud, falling back to local:", error);
      
      // Fallback to local storage if the cloud is unreachable
      const localSequences = JSON.parse(localStorage.getItem('leviva_sequenceBank') || '[]');
      setSequenceBank(localSequences);
      setCurrentView('sequence-bank');
    }
  };

  // --- AUTO-SAVE EFFECTS ---
  useEffect(() => { localStorage.setItem('leviva_testBank', JSON.stringify(testBank)); }, [testBank]);
  useEffect(() => { localStorage.setItem('leviva_patientBank', JSON.stringify(patientBank)); }, [patientBank]);
  useEffect(() => { localStorage.setItem('leviva_folders', JSON.stringify(customFolders)); }, [customFolders]);

  // --- SAVE/UPDATE FUNCTIONS ---
  const handleSaveTestToBank = async (title: string, description: string, category: TestCategory, configData: any, existingId?: string) => {
    const formattedSlides = configData.map((slide: any, index: number) => ({
      ...slide,
      slideNumber: index + 1
    }));

    const payload = {
      testName: title || 'Untitled Test',
      description: description || 'No description provided.',
      testType: category,
      slides: formattedSlides
    };

    // Check if the ID is a real 24-character MongoDB ID
    const isMongoId = existingId && /^[0-9a-fA-F]{24}$/.test(existingId);
    const method = isMongoId ? 'PUT' : 'POST';
    const url = isMongoId ? `${API_URL}/api/tests/${existingId}` : `${API_URL}/api/tests`;

    try {
      const response = await fetch(url, {
        method: method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        const savedData = await response.json(); // This contains the REAL database _id
        alert(`✅ "${payload.testName}" successfully saved to the Cloud Database!`);
        
        // Save the REAL MongoDB _id into your local storage
        const realId = savedData._id;
        
        const newTest: SavedTest = {
          id: realId, 
          title: payload.testName, 
          description: payload.description,
          category, 
          folder: category, 
          configData, 
          dateCreated: new Date().toLocaleString(), 
          lastModified: new Date().toLocaleString()
        };
        
        if (existingId) {
          // If we updated, map over the bank and replace the old one
          const updatedBank = testBank.map(test => test.id === existingId ? { ...newTest, folder: test.folder } : test);
          setTestBank(updatedBank);
        } else {
          // If brand new, add to the end
          setTestBank([...testBank, newTest]);
        }
        
        setEditTarget(null); 
        setCurrentView('bank'); 
      } else {
        const errorData = await response.json();
        alert(`❌ Backend rejected the data. Reason: ${errorData.error}`);
      }
    } catch (error) {
      console.error("Database connection error:", error);
      alert("❌ Could not connect to backend.");
    }  
  };

  // ---- DELETE HANDLERS -----
  const handleDeleteTest = async (testId: string) => {
    if (!window.confirm("Are you sure you want to permanently delete this test?")) return;
    
    // If it's a cloud test, delete it from the server
    if (/^[0-9a-fA-F]{24}$/.test(testId)) {
      try {
        await fetch(`${API_URL}/api/tests/${testId}`, { method: 'DELETE' });
      } catch (e) { console.error("Failed to delete from cloud", e); }
    }
    // Remove from local React state
    setTestBank(testBank.filter(t => t.id !== testId));
  };

  const handleDeleteSequence = async (sequenceId: string) => {
    if (!window.confirm("Are you sure you want to permanently delete this sequence?")) return;
    
    // Delete from cloud
    try {
      await fetch(`${API_URL}/api/sequences/${sequenceId}`, { method: 'DELETE' });
    } catch (e) { console.error("Failed to delete from cloud", e); }

    // Delete from local backup
    const localSequences = JSON.parse(localStorage.getItem('leviva_sequenceBank') || '[]');
    const updatedLocal = localSequences.filter((s: any) => s._id !== sequenceId);
    localStorage.setItem('leviva_sequenceBank', JSON.stringify(updatedLocal));

    // Remove from local React state
    setSequenceBank(sequenceBank.filter(s => s._id !== sequenceId));
  };

  // --- BACKUP FUNCTIONS ---
  const handleExportBank = () => {
    const dataString = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(testBank, null, 2));
    const anchor = document.createElement('a');
    anchor.href = dataString;
    anchor.download = `leviva_testbank_backup_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
  };

  const handleImportBank = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const importedBank = JSON.parse(event.target?.result as string);
        if (Array.isArray(importedBank)) {
          setTestBank(importedBank);
          
          // --- FIX: Extract new folders and merge them so they render ---
          const importedFolders = importedBank.map((test: SavedTest) => test.folder || test.category);
          const uniqueFolders = Array.from(new Set([...customFolders, ...importedFolders]));
          setCustomFolders(uniqueFolders);

          alert("Test Bank successfully restored from backup!");
        }
      } catch (err) {
        alert("Invalid backup file.");
      }
    };
    reader.readAsText(file);
  };

  const handleSavePatient = (record: PatientIntake) => {
    const existingIndex = patientBank.findIndex((p) => p.id === record.id);
    if (existingIndex >= 0) {
      const updated = patientBank.map((p) => (p.id === record.id ? record : p));
      setPatientBank(updated);
      alert(`עודכן בהצלחה: ${record.child.firstName} ${record.child.lastName}`);
    } else {
      setPatientBank([...patientBank, record]);
      alert(`נשמר בהצלחה: ${record.child.firstName} ${record.child.lastName}`);
    }
    setEditPatientTarget(null);
    setCurrentView('patients');
  };

  // --- FOLDER MANAGEMENT FUNCTIONS ---
  const handleCreateNewFolder = () => {
    const folderName = prompt("Enter a name for the new folder:");
    if (folderName && folderName.trim() !== '') {
      if (!customFolders.includes(folderName.trim())) {
        setCustomFolders([...customFolders, folderName.trim()]);
      } else {
        alert("A folder with this name already exists.");
      }
    }
  };

  const handleMoveTest = (testId: string, targetFolder: string) => {
    const updatedBank = testBank.map(test => 
      test.id === testId ? { ...test, folder: targetFolder } : test
    );
    setTestBank(updatedBank);
  };

  // --- ROUTER LOGIC ---
  const renderView = () => {
    switch (currentView) {
      case 'home':
        return (
          <div style={{ textAlign: 'center', marginTop: '50px' }}>
            <h1>Neurocognitive Clinical Dashboard</h1>
            <div style={{ display: 'flex', justifyContent: 'center', gap: '30px', marginTop: '40px', flexWrap: 'wrap' }}>
              {isLabAdmin && (
                <button onClick={() => { setEditTarget(null); setCurrentView('creator-menu'); }} style={bigBtnStyle}>🛠️ Create New Test</button>
              )}
              <button onClick={() => setCurrentView('bank')} style={bigBtnStyle}>📁 Open Test Bank ({testBank.length})</button>
              <button onClick={openSequenceBank} style={{...bigBtnStyle, borderColor: 'green', backgroundColor: '#e8f5e9'}}>
                🔗 Sequence Bank
              </button>
              <button onClick={() => { setEditPatientTarget(null); setCurrentView('patient-intake'); }} style={bigBtnStyle}>🧒 New Patient Intake</button>
              <button onClick={() => setCurrentView('patients')} style={bigBtnStyle}>🗂️ Patient Bank ({patientBank.length})</button>
            </div>
          </div>
        );

      case 'creator-menu':
        return (
          <div style={{ maxWidth: '600px', margin: '0 auto', marginTop: '30px' }}>
            <h2>Select a Template to Build:</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
              <button onClick={() => setCurrentView('create-auditory')} style={menuBtn}>1. Auditory Repetition</button>
              <button onClick={() => setCurrentView('create-visual-assoc')} style={menuBtn}>2. Visual Association</button>
              <button onClick={() => setCurrentView('create-reading')} style={menuBtn}>3. Reading Aloud</button>
              <button onClick={() => setCurrentView('create-binary')} style={menuBtn}>4. Binary Choice Suite</button>
              <button onClick={() => setCurrentView('create-target')} style={menuBtn}>5. Visual Target Identification</button>
              <button onClick={() => setCurrentView('create-naming')} style={menuBtn}>6. Naming Task (שמש צדפים)</button>
              {isLabAdmin && (
                <button onClick={() => { setEditSequenceTarget(null); setCurrentView('create-sequence'); }} style={{...menuBtn, backgroundColor: '#eef8ff', borderColor: 'darkblue', fontWeight: 'bold'}}>7. 🔗 Master Sequence Builder</button>
              )}
            </div>
          </div>
        );

      case 'bank':
        const groupedBank = testBank.reduce((acc, test) => {
          const folderKey = test.folder || test.category; 
          if (!acc[folderKey]) acc[folderKey] = [];
          acc[folderKey].push(test);
          return acc;
        }, {} as Record<string, SavedTest[]>);

        customFolders.forEach(f => { if (!groupedBank[f]) groupedBank[f] = []; });

        return (
          <div style={{ maxWidth: '800px', margin: '0 auto', marginTop: '30px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h2>Clinical Test Bank</h2>
              
              <div style={{ display: 'flex' }}>
                <button onClick={handleCreateNewFolder} style={{ padding: '8px 16px', backgroundColor: 'darkblue', color: 'white', borderRadius: '4px', cursor: 'pointer' }}>
                  + New Folder
                </button>
                <button onClick={handleExportBank} style={{ padding: '8px 16px', backgroundColor: '#4CAF50', color: 'white', borderRadius: '4px', cursor: 'pointer', marginLeft: '10px' }}>
                  📥 Backup Bank
                </button>
                <label style={{ padding: '8px 16px', backgroundColor: '#ff9800', color: 'white', borderRadius: '4px', cursor: 'pointer', marginLeft: '10px' }}>
                  📤 Restore Bank
                  <input type="file" accept=".json" onChange={handleImportBank} style={{ display: 'none' }} />
                </label>
              </div>
            </div>

            {customFolders.map((folderName) => (
              <div key={folderName} style={{ border: '2px solid #ccc', borderRadius: '8px', overflow: 'hidden', marginBottom: '15px' }}>
                <div 
                  onClick={() => setExpandedFolder(expandedFolder === folderName ? null : folderName)}
                  style={{ padding: '15px', backgroundColor: '#eef8ff', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', fontWeight: 'bold' }}
                >
                  <span>📁 {folderName} ({groupedBank[folderName]?.length || 0} Tests)</span>
                  <span>{expandedFolder === folderName ? '▼' : '▶'}</span>
                </div>

                {expandedFolder === folderName && (
                  <div style={{ padding: '15px', display: 'flex', flexDirection: 'column', gap: '10px', backgroundColor: '#fafafa' }}>
                    {groupedBank[folderName]?.length === 0 ? (
                      <p style={{ color: '#777', fontStyle: 'italic', margin: 0 }}>This folder is empty.</p>
                    ) : (
                      groupedBank[folderName].map((test) => (
                        <div key={test.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px', border: '1px solid #ddd', borderRadius: '4px', backgroundColor: 'white' }}>
                          <div style={{ flex: 1 }}>
                            <strong style={{ fontSize: '18px', color: 'darkblue' }}>{test.title}</strong>
                            <p style={{ margin: '5px 0', fontSize: '14px', color: '#555' }}>{test.description}</p>
                            
                            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '10px' }}>
                              <span style={{ fontSize: '12px', color: 'gray' }}>Move to:</span>
                              <select 
                                value={test.folder || test.category} 
                                onChange={(e) => handleMoveTest(test.id, e.target.value)}
                                style={{ padding: '4px', fontSize: '12px', borderRadius: '4px' }}
                              >
                                {customFolders.map(f => <option key={f} value={f}>{f}</option>)}
                              </select>
                            </div>
                          </div>
                          
                          <div style={{ display: 'flex', gap: '10px', marginLeft: '20px' }}>
                            
                            {isLabAdmin && (
                              <>
                                <button 
                                  onClick={() => handleDeleteTest(test.id)} 
                                  style={{ padding: '8px 12px', backgroundColor: '#f44336', color: 'white', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                                >
                                  🗑️
                                </button>
                                
                                <button 
                                  onClick={() => {
                                    setEditTarget(test);
                                    let route = '';
                                    if(test.category === 'Auditory') route = 'create-auditory';
                                    if(test.category === 'VisualAssociation') route = 'create-visual-assoc';
                                    if(test.category === 'ReadingAloud') route = 'create-reading';
                                    if(test.category === 'BinaryChoice') route = 'create-binary';
                                    if(test.category === 'TargetID') route = 'create-target';
                                    // NEW: Naming Task edit route
                                    if(test.category === 'Naming') route = 'create-naming';
                                    setCurrentView(route);
                                  }} 
                                  style={{ padding: '8px 16px', backgroundColor: '#ffc107', color: 'black', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                                >✏️ Edit</button>
                              </>
                            )}
                            <button 
                              onClick={() => {
                                setActiveRunConfig(test);
                                setCurrentView(`run-${test.category.toLowerCase()}`);
                              }} 
                              style={{ padding: '8px 16px', backgroundColor: 'green', color: 'white', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                            >▶ Run</button>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        );
      
      case 'sequence-bank':
        return (
          <div style={{ maxWidth: '800px', margin: '0 auto', marginTop: '30px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h2>Master Sequence Bank (Cloud)</h2>
            </div>
            
            {sequenceBank.length === 0 ? (
              <p>No sequences found in the database.</p>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {sequenceBank.map(seq => (
                  <div key={seq._id} style={{ display: 'flex', justifyContent: 'space-between', padding: '15px', border: '1px solid #ddd', borderRadius: '8px', backgroundColor: 'white' }}>
                    <div>
                      <strong style={{ fontSize: '18px', color: 'darkblue' }}>{seq.sequenceName || 'Untitled Sequence'}</strong>
                      <p style={{ margin: '5px 0', fontSize: '14px', color: '#555' }}>{seq.description}</p>
                      <span style={{ fontSize: '12px', fontWeight: 'bold', color: 'gray' }}>{seq.steps?.length || 0} Steps</span>
                    </div>
                    
                    <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                     
                    {isLabAdmin && (
                      <>
                        <button 
                          onClick={() => handleDeleteSequence(seq._id)} 
                          style={{ padding: '8px 16px', backgroundColor: '#f44336', color: 'white', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                        >
                          🗑️ Delete
                        </button>

                        <button
                          onClick={() => {
                            setEditSequenceTarget(seq);
                            setCurrentView('create-sequence');
                          }}
                          style={{ padding: '8px 16px', backgroundColor: '#ffc107', color: 'black', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                        >
                          ✏️ Edit
                        </button>
                      </>
                    )}

                     <button 
                        onClick={() => {
                          setActiveSequenceId(seq._id);
                          setIsPublicLinkAccess(false); // admin preview — keep the skip control available
                          setCurrentView('public-run-sequence');
                        }}
                        style={{ padding: '8px 16px', backgroundColor: '#2196F3', color: 'white', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                      >
                        ▶ Run Sequence
                      </button>

                     <button 
                        onClick={() => {
                          // Generate the link using your React app's URL dynamically
                          const link = `${window.location.origin}/run/${seq._id}`;
                          navigator.clipboard.writeText(link);
                          alert(`✅ Link copied to clipboard!\n\n${link}`);
                        }}
                        style={{ padding: '8px 16px', backgroundColor: '#4CAF50', color: 'white', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                      >
                        🔗 Get Shareable Link
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        );  

      case 'create-auditory': return <AuditoryRepetitionWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'Auditory', data, editTarget?.id)} />;
      case 'create-visual-assoc': return <VisualAssociationWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'VisualAssociation', data, editTarget?.id)} />;
      case 'create-reading': return <ReadingAloudWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'ReadingAloud', data, editTarget?.id)} />;
      case 'create-binary': return <BinaryChoiceWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'BinaryChoice', data, editTarget?.id)} />;
      case 'create-target': return <VisualTargetWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'TargetID', data, editTarget?.id)} />;
      case 'create-naming': return <NamingTaskWorkspace key={editTarget?.id || 'new'} initialData={editTarget} onSave={(data, meta) => handleSaveTestToBank(meta.title, meta.description, 'Naming', data, editTarget?.id)} />;
      case 'create-sequence':
        return (
          <SequenceBuilder
            key={editSequenceTarget?._id || 'new-sequence'}
            initialData={editSequenceTarget}
            onSaveComplete={() => { setEditSequenceTarget(null); openSequenceBank(); }}
            onCancel={() => { setEditSequenceTarget(null); setCurrentView('sequence-bank'); }}
          />
        );

      case 'public-run-sequence':
        return activeSequenceId ? (
          <PublicSequenceRunner
            sequenceId={activeSequenceId}
            isPublicLink={isPublicLinkAccess}
            onExit={() => {
              setActiveSequenceId(null);
              setIsPublicLinkAccess(false);
              // Clean the /run/:id path back to / so a refresh doesn't re-trigger the deep link
              window.history.pushState({}, '', '/');
              setCurrentView('home');
            }}
          />
        ) : (
          <div>No sequence selected.</div>
        );
      
      case 'run-auditory': return <AuditoryRepetitionRunner configuredAudioTracks={activeRunConfig?.configData} />;
      case 'run-visualassociation': return <VisualAssociationRunner configuredSlides={activeRunConfig?.configData} />;
      case 'run-readingaloud': return <ReadingAloudRunner configuredTasks={activeRunConfig?.configData} />;
      case 'run-binarychoice': return <BinaryChoiceRunner configuredTrials={activeRunConfig?.configData} testMode={activeRunConfig?.configData[0]?.testType} />;
      case 'run-targetid': return <TargetRunnerEngine configuredSlides={activeRunConfig?.configData} />;
      case 'run-naming': return <NamingTaskRunner configuredSlides={activeRunConfig?.configData} />;

      case 'patient-intake':
        return <PatientIntakeWorkspace key={editPatientTarget?.id || 'new-patient'} initialData={editPatientTarget} onSave={(record) => handleSavePatient(record)} />;

      case 'patients':
        return (
          <PatientBank
            patients={patientBank}
            onEdit={(patient) => { setEditPatientTarget(patient); setCurrentView('patient-intake'); }}
            onSelectForTesting={(patient) => { setActivePatientForTesting(patient); setCurrentView('select-tests-for-patient'); }}
          />
        );

      case 'select-tests-for-patient':
        return (
          <div style={{ maxWidth: '700px', margin: '0 auto', marginTop: '30px', direction: 'rtl' }}>
            <h2>בחירת מבחנים מתאימים</h2>
            {activePatientForTesting ? (
              <div style={{ padding: '20px', border: '1px solid #ddd', borderRadius: '8px', backgroundColor: '#fafafa' }}>
                <p>מטופל/ת: <strong>{activePatientForTesting.child.firstName} {activePatientForTesting.child.lastName}</strong></p>
                <p style={{ color: '#777' }}>מנגנון הבחירה האוטומטית של מבחנים מתאימים, ומנגנון השוואת הנורמות יתווספו בהמשך.</p>
              </div>
            ) : <p>לא נבחר מטופל.</p>}
          </div>
        );

      default: return <div>Screen not found</div>;
    }
  };

  

  return (
    <div>
      {isPublicLinkAccess ? (
        // Patient tunnel: renders straight to the sequence runner, no Clerk UI, no admin chrome.
        <main style={{ padding: '20px' }}>
          {renderView()}
        </main>
      ) : (
        <>
          <SignedOut>
            <div style={{ maxWidth: '400px', margin: '100px auto', textAlign: 'center', padding: '40px', border: '1px solid #ddd', borderRadius: '8px' }}>
              <h2>Leviva Clinical Dashboard</h2>
              <p style={{ color: '#666', marginBottom: '25px' }}>Please sign in to continue.</p>
              <SignInButton mode="modal">
                <button style={{ padding: '12px 30px', backgroundColor: 'darkblue', color: 'white', border: 'none', borderRadius: '6px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer' }}>
                  Sign In
                </button>
              </SignInButton>
            </div>
          </SignedOut>

          <SignedIn>
            <header style={{ backgroundColor: 'darkblue', color: 'white', padding: '15px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h3 style={{ margin: 0 }}>
                NeuroPlatform Admin
                {userRole && <span style={{ fontSize: '12px', fontWeight: 'normal', marginLeft: '10px', opacity: 0.8 }}>({userRole === 'lab_admin' ? 'Lab Admin' : 'Clinician'})</span>}
              </h3>
              <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
                {currentView !== 'home' && (
                  <button onClick={() => setCurrentView('home')} style={{ padding: '8px 15px', cursor: 'pointer', backgroundColor: 'white', color: 'darkblue', border: 'none', borderRadius: '4px', fontWeight: 'bold' }}>
                    ← Home Dashboard
                  </button>
                )}
                <UserButton afterSignOutUrl="/" />
              </div>
            </header>
            <main style={{ padding: '20px' }}>
              {renderView()}
            </main>
          </SignedIn>
        </>
      )}
    </div>
  );
}

const bigBtnStyle = { padding: '30px', fontSize: '20px', cursor: 'pointer', backgroundColor: '#eef8ff', border: '2px solid darkblue', borderRadius: '12px', fontWeight: 'bold' };
const menuBtn = { padding: '15px', fontSize: '16px', cursor: 'pointer', backgroundColor: '#f0f0f0', border: '1px solid #ccc', borderRadius: '6px', textAlign: 'left' as const };